steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/api:$COMMIT_SHA
      - -t
      - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/api:latest
      - -f
      - apps/api/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/api:$COMMIT_SHA
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/api:latest
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    args:
      - gcloud
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/api:$COMMIT_SHA
      - --region=$_DEPLOY_REGION
      - --platform=managed
      - --port=4000
      - --allow-unauthenticated

substitutions:
  _GCR_HOSTNAME: gcr.io
  _SERVICE_NAME: stageholder-meridian-api
  _DEPLOY_REGION: asia-southeast1

options:
  logging: CLOUD_LOGGING_ONLY
