steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/pwa:$COMMIT_SHA
      - -t
      - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/pwa:latest
      - --build-arg
      - NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL
      - -f
      - apps/pwa/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/pwa:$COMMIT_SHA
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/pwa:latest
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    args:
      - gcloud
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/pwa:$COMMIT_SHA
      - --region=$_DEPLOY_REGION
      - --platform=managed
      - --port=3000
      - --allow-unauthenticated

substitutions:
  _GCR_HOSTNAME: gcr.io
  _SERVICE_NAME: meridian-pwa
  _DEPLOY_REGION: asia-southeast2
  _NEXT_PUBLIC_API_URL: https://api.meridian.stageholder.com/api/v1

options:
  logging: CLOUD_LOGGING_ONLY
