// Bundles entry.ts (the custom tentap web editor) into a single self-contained
// HTML string, written to src/todos/quick-add-editor-html.ts and imported by
// smart-todo-input.native.tsx as the tentap `customSource`.
//
// Regenerate after editing entry.ts:  bun run packages/features/editor-web/build.mjs
import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");

// Force a SINGLE React/ReactDOM instance. Without this, esbuild resolves the
// root, the features-local, AND tentap's nested React copies — multiple React
// instances → "invalid hook call" → the editor never mounts (blank field).
// esbuild package-name aliases also cover subpaths (react/jsx-runtime,
// react-dom/client).
const dedupeReactAlias = {
  react: resolve(repoRoot, "node_modules/react"),
  "react-dom": resolve(repoRoot, "node_modules/react-dom"),
  scheduler: resolve(repoRoot, "node_modules/scheduler"),
};

// esbuild's transitive resolution of tentap's nested react-dom erroneously drags
// in react-native + expo-* (which contain Flow syntax esbuild can't parse and
// which a BROWSER editor never runs). Stub the whole native/expo surface to an
// empty module — nothing in the web editor's real code path touches it.
const stubNativePlugin = {
  name: "stub-native",
  setup(b) {
    b.onResolve(
      { filter: /^(react-native|react-native\/.*|@react-native\/.*|expo|expo-.*|@expo\/.*)$/ },
      () => ({ path: "stub-native", namespace: "stub-native" }),
    );
    b.onLoad({ filter: /.*/, namespace: "stub-native" }, () => ({
      contents: "export default {}; export const Platform = { OS: 'web' };",
      loader: "js",
    }));
  },
};

const result = await build({
  entryPoints: [resolve(here, "entry.ts")],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2019",
  minify: true,
  write: false,
  define: { "process.env.NODE_ENV": '"production"' },
  alias: dedupeReactAlias,
  plugins: [stubNativePlugin],
});

let js = result.outputFiles[0].text;
// Stop the inlined module from prematurely closing the <script> element.
js = js.replace(/<\/script/gi, "<\\/script");

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<title>QuickAddEditor</title>
<style>
  html, body { margin: 0; padding: 0; background: transparent; }
  #root > div:nth-of-type(1) { position: absolute; top: 0; bottom: 0; left: 0; right: 0; height: 100%; width: 100%; overflow: auto; }
  #root div .ProseMirror { min-height: 100%; overflow: visible; }
  .ProseMirror:focus { outline: none; }
</style>
</head>
<body>
<div id="root"></div>
<script type="module">${js}</script>
</body>
</html>`;

const out =
  "// AUTO-GENERATED by packages/features/editor-web/build.mjs — DO NOT EDIT.\n" +
  "// Regenerate: bun run packages/features/editor-web/build.mjs\n" +
  "/* eslint-disable */\n" +
  "export const QUICK_ADD_EDITOR_HTML = " +
  JSON.stringify(html) +
  ";\n";

const outPath = resolve(here, "../src/todos/quick-add-editor-html.ts");
writeFileSync(outPath, out);
console.log(
  `wrote ${outPath}\n  bundle: ${Math.round(js.length / 1024)} KB JS, ${Math.round(out.length / 1024)} KB total`,
);
