/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthRouteRouteImport } from "./routes/_auth/route";
import { Route as AppRouteRouteImport } from "./routes/_app/route";
import { Route as AppIndexRouteImport } from "./routes/_app/index";
import { Route as AuthOnboardingRouteImport } from "./routes/_auth/onboarding";
import { Route as AuthGoodbyeRouteImport } from "./routes/_auth/goodbye";
import { Route as AppJourneyRouteImport } from "./routes/_app/journey";
import { Route as AppCalendarRouteImport } from "./routes/_app/calendar";
import { Route as AppTodosRouteRouteImport } from "./routes/_app/todos/route";
import { Route as AppJournalRouteRouteImport } from "./routes/_app/journal/route";
import { Route as AppTodosIndexRouteImport } from "./routes/_app/todos/index";
import { Route as AppSettingsIndexRouteImport } from "./routes/_app/settings/index";
import { Route as AppJournalIndexRouteImport } from "./routes/_app/journal/index";
import { Route as AppHabitsIndexRouteImport } from "./routes/_app/habits/index";
import { Route as AuthAuthLoginRouteImport } from "./routes/_auth/auth.login";
import { Route as AuthAuthErrorRouteImport } from "./routes/_auth/auth.error";
import { Route as AuthAuthCallbackRouteImport } from "./routes/_auth/auth.callback";
import { Route as AppTodosUpcomingRouteImport } from "./routes/_app/todos/upcoming";
import { Route as AppTodosInboxRouteImport } from "./routes/_app/todos/inbox";
import { Route as AppTodosCompletedRouteImport } from "./routes/_app/todos/completed";
import { Route as AppTodosListIdRouteImport } from "./routes/_app/todos/$listId";
import { Route as AppJournalNewRouteImport } from "./routes/_app/journal/new";
import { Route as AppJournalIdRouteImport } from "./routes/_app/journal/$id";
import { Route as AppHabitsIdRouteImport } from "./routes/_app/habits/$id";
import { Route as AppSettingsBillingIndexRouteImport } from "./routes/_app/settings/billing/index";
import { Route as AppSettingsBillingUpgradeRouteImport } from "./routes/_app/settings/billing/upgrade";
import { Route as AppSettingsBillingSuccessRouteImport } from "./routes/_app/settings/billing/success";

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRouteRoute = AppRouteRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRouteRoute,
} as any);
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthGoodbyeRoute = AuthGoodbyeRouteImport.update({
  id: "/goodbye",
  path: "/goodbye",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AppJourneyRoute = AppJourneyRouteImport.update({
  id: "/journey",
  path: "/journey",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: "/calendar",
  path: "/calendar",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppTodosRouteRoute = AppTodosRouteRouteImport.update({
  id: "/todos",
  path: "/todos",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppJournalRouteRoute = AppJournalRouteRouteImport.update({
  id: "/journal",
  path: "/journal",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppTodosIndexRoute = AppTodosIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppTodosRouteRoute,
} as any);
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppJournalIndexRoute = AppJournalIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppJournalRouteRoute,
} as any);
const AppHabitsIndexRoute = AppHabitsIndexRouteImport.update({
  id: "/habits/",
  path: "/habits/",
  getParentRoute: () => AppRouteRoute,
} as any);
const AuthAuthLoginRoute = AuthAuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthAuthErrorRoute = AuthAuthErrorRouteImport.update({
  id: "/auth/error",
  path: "/auth/error",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthAuthCallbackRoute = AuthAuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AppTodosUpcomingRoute = AppTodosUpcomingRouteImport.update({
  id: "/upcoming",
  path: "/upcoming",
  getParentRoute: () => AppTodosRouteRoute,
} as any);
const AppTodosInboxRoute = AppTodosInboxRouteImport.update({
  id: "/inbox",
  path: "/inbox",
  getParentRoute: () => AppTodosRouteRoute,
} as any);
const AppTodosCompletedRoute = AppTodosCompletedRouteImport.update({
  id: "/completed",
  path: "/completed",
  getParentRoute: () => AppTodosRouteRoute,
} as any);
const AppTodosListIdRoute = AppTodosListIdRouteImport.update({
  id: "/$listId",
  path: "/$listId",
  getParentRoute: () => AppTodosRouteRoute,
} as any);
const AppJournalNewRoute = AppJournalNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => AppJournalRouteRoute,
} as any);
const AppJournalIdRoute = AppJournalIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => AppJournalRouteRoute,
} as any);
const AppHabitsIdRoute = AppHabitsIdRouteImport.update({
  id: "/habits/$id",
  path: "/habits/$id",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppSettingsBillingIndexRoute = AppSettingsBillingIndexRouteImport.update({
  id: "/settings/billing/",
  path: "/settings/billing/",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppSettingsBillingUpgradeRoute =
  AppSettingsBillingUpgradeRouteImport.update({
    id: "/settings/billing/upgrade",
    path: "/settings/billing/upgrade",
    getParentRoute: () => AppRouteRoute,
  } as any);
const AppSettingsBillingSuccessRoute =
  AppSettingsBillingSuccessRouteImport.update({
    id: "/settings/billing/success",
    path: "/settings/billing/success",
    getParentRoute: () => AppRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute;
  "/journal": typeof AppJournalRouteRouteWithChildren;
  "/todos": typeof AppTodosRouteRouteWithChildren;
  "/calendar": typeof AppCalendarRoute;
  "/journey": typeof AppJourneyRoute;
  "/goodbye": typeof AuthGoodbyeRoute;
  "/onboarding": typeof AuthOnboardingRoute;
  "/habits/$id": typeof AppHabitsIdRoute;
  "/journal/$id": typeof AppJournalIdRoute;
  "/journal/new": typeof AppJournalNewRoute;
  "/todos/$listId": typeof AppTodosListIdRoute;
  "/todos/completed": typeof AppTodosCompletedRoute;
  "/todos/inbox": typeof AppTodosInboxRoute;
  "/todos/upcoming": typeof AppTodosUpcomingRoute;
  "/auth/callback": typeof AuthAuthCallbackRoute;
  "/auth/error": typeof AuthAuthErrorRoute;
  "/auth/login": typeof AuthAuthLoginRoute;
  "/habits/": typeof AppHabitsIndexRoute;
  "/journal/": typeof AppJournalIndexRoute;
  "/settings/": typeof AppSettingsIndexRoute;
  "/todos/": typeof AppTodosIndexRoute;
  "/settings/billing/success": typeof AppSettingsBillingSuccessRoute;
  "/settings/billing/upgrade": typeof AppSettingsBillingUpgradeRoute;
  "/settings/billing/": typeof AppSettingsBillingIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof AppIndexRoute;
  "/calendar": typeof AppCalendarRoute;
  "/journey": typeof AppJourneyRoute;
  "/goodbye": typeof AuthGoodbyeRoute;
  "/onboarding": typeof AuthOnboardingRoute;
  "/habits/$id": typeof AppHabitsIdRoute;
  "/journal/$id": typeof AppJournalIdRoute;
  "/journal/new": typeof AppJournalNewRoute;
  "/todos/$listId": typeof AppTodosListIdRoute;
  "/todos/completed": typeof AppTodosCompletedRoute;
  "/todos/inbox": typeof AppTodosInboxRoute;
  "/todos/upcoming": typeof AppTodosUpcomingRoute;
  "/auth/callback": typeof AuthAuthCallbackRoute;
  "/auth/error": typeof AuthAuthErrorRoute;
  "/auth/login": typeof AuthAuthLoginRoute;
  "/habits": typeof AppHabitsIndexRoute;
  "/journal": typeof AppJournalIndexRoute;
  "/settings": typeof AppSettingsIndexRoute;
  "/todos": typeof AppTodosIndexRoute;
  "/settings/billing/success": typeof AppSettingsBillingSuccessRoute;
  "/settings/billing/upgrade": typeof AppSettingsBillingUpgradeRoute;
  "/settings/billing": typeof AppSettingsBillingIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_app": typeof AppRouteRouteWithChildren;
  "/_auth": typeof AuthRouteRouteWithChildren;
  "/_app/journal": typeof AppJournalRouteRouteWithChildren;
  "/_app/todos": typeof AppTodosRouteRouteWithChildren;
  "/_app/calendar": typeof AppCalendarRoute;
  "/_app/journey": typeof AppJourneyRoute;
  "/_auth/goodbye": typeof AuthGoodbyeRoute;
  "/_auth/onboarding": typeof AuthOnboardingRoute;
  "/_app/": typeof AppIndexRoute;
  "/_app/habits/$id": typeof AppHabitsIdRoute;
  "/_app/journal/$id": typeof AppJournalIdRoute;
  "/_app/journal/new": typeof AppJournalNewRoute;
  "/_app/todos/$listId": typeof AppTodosListIdRoute;
  "/_app/todos/completed": typeof AppTodosCompletedRoute;
  "/_app/todos/inbox": typeof AppTodosInboxRoute;
  "/_app/todos/upcoming": typeof AppTodosUpcomingRoute;
  "/_auth/auth/callback": typeof AuthAuthCallbackRoute;
  "/_auth/auth/error": typeof AuthAuthErrorRoute;
  "/_auth/auth/login": typeof AuthAuthLoginRoute;
  "/_app/habits/": typeof AppHabitsIndexRoute;
  "/_app/journal/": typeof AppJournalIndexRoute;
  "/_app/settings/": typeof AppSettingsIndexRoute;
  "/_app/todos/": typeof AppTodosIndexRoute;
  "/_app/settings/billing/success": typeof AppSettingsBillingSuccessRoute;
  "/_app/settings/billing/upgrade": typeof AppSettingsBillingUpgradeRoute;
  "/_app/settings/billing/": typeof AppSettingsBillingIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/journal"
    | "/todos"
    | "/calendar"
    | "/journey"
    | "/goodbye"
    | "/onboarding"
    | "/habits/$id"
    | "/journal/$id"
    | "/journal/new"
    | "/todos/$listId"
    | "/todos/completed"
    | "/todos/inbox"
    | "/todos/upcoming"
    | "/auth/callback"
    | "/auth/error"
    | "/auth/login"
    | "/habits/"
    | "/journal/"
    | "/settings/"
    | "/todos/"
    | "/settings/billing/success"
    | "/settings/billing/upgrade"
    | "/settings/billing/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/calendar"
    | "/journey"
    | "/goodbye"
    | "/onboarding"
    | "/habits/$id"
    | "/journal/$id"
    | "/journal/new"
    | "/todos/$listId"
    | "/todos/completed"
    | "/todos/inbox"
    | "/todos/upcoming"
    | "/auth/callback"
    | "/auth/error"
    | "/auth/login"
    | "/habits"
    | "/journal"
    | "/settings"
    | "/todos"
    | "/settings/billing/success"
    | "/settings/billing/upgrade"
    | "/settings/billing";
  id:
    | "__root__"
    | "/_app"
    | "/_auth"
    | "/_app/journal"
    | "/_app/todos"
    | "/_app/calendar"
    | "/_app/journey"
    | "/_auth/goodbye"
    | "/_auth/onboarding"
    | "/_app/"
    | "/_app/habits/$id"
    | "/_app/journal/$id"
    | "/_app/journal/new"
    | "/_app/todos/$listId"
    | "/_app/todos/completed"
    | "/_app/todos/inbox"
    | "/_app/todos/upcoming"
    | "/_auth/auth/callback"
    | "/_auth/auth/error"
    | "/_auth/auth/login"
    | "/_app/habits/"
    | "/_app/journal/"
    | "/_app/settings/"
    | "/_app/todos/"
    | "/_app/settings/billing/success"
    | "/_app/settings/billing/upgrade"
    | "/_app/settings/billing/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AppRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_auth/onboarding": {
      id: "/_auth/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof AuthOnboardingRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/goodbye": {
      id: "/_auth/goodbye";
      path: "/goodbye";
      fullPath: "/goodbye";
      preLoaderRoute: typeof AuthGoodbyeRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_app/journey": {
      id: "/_app/journey";
      path: "/journey";
      fullPath: "/journey";
      preLoaderRoute: typeof AppJourneyRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/calendar": {
      id: "/_app/calendar";
      path: "/calendar";
      fullPath: "/calendar";
      preLoaderRoute: typeof AppCalendarRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/todos": {
      id: "/_app/todos";
      path: "/todos";
      fullPath: "/todos";
      preLoaderRoute: typeof AppTodosRouteRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/journal": {
      id: "/_app/journal";
      path: "/journal";
      fullPath: "/journal";
      preLoaderRoute: typeof AppJournalRouteRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/todos/": {
      id: "/_app/todos/";
      path: "/";
      fullPath: "/todos/";
      preLoaderRoute: typeof AppTodosIndexRouteImport;
      parentRoute: typeof AppTodosRouteRoute;
    };
    "/_app/settings/": {
      id: "/_app/settings/";
      path: "/settings";
      fullPath: "/settings/";
      preLoaderRoute: typeof AppSettingsIndexRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/journal/": {
      id: "/_app/journal/";
      path: "/";
      fullPath: "/journal/";
      preLoaderRoute: typeof AppJournalIndexRouteImport;
      parentRoute: typeof AppJournalRouteRoute;
    };
    "/_app/habits/": {
      id: "/_app/habits/";
      path: "/habits";
      fullPath: "/habits/";
      preLoaderRoute: typeof AppHabitsIndexRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_auth/auth/login": {
      id: "/_auth/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthAuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/auth/error": {
      id: "/_auth/auth/error";
      path: "/auth/error";
      fullPath: "/auth/error";
      preLoaderRoute: typeof AuthAuthErrorRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/auth/callback": {
      id: "/_auth/auth/callback";
      path: "/auth/callback";
      fullPath: "/auth/callback";
      preLoaderRoute: typeof AuthAuthCallbackRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_app/todos/upcoming": {
      id: "/_app/todos/upcoming";
      path: "/upcoming";
      fullPath: "/todos/upcoming";
      preLoaderRoute: typeof AppTodosUpcomingRouteImport;
      parentRoute: typeof AppTodosRouteRoute;
    };
    "/_app/todos/inbox": {
      id: "/_app/todos/inbox";
      path: "/inbox";
      fullPath: "/todos/inbox";
      preLoaderRoute: typeof AppTodosInboxRouteImport;
      parentRoute: typeof AppTodosRouteRoute;
    };
    "/_app/todos/completed": {
      id: "/_app/todos/completed";
      path: "/completed";
      fullPath: "/todos/completed";
      preLoaderRoute: typeof AppTodosCompletedRouteImport;
      parentRoute: typeof AppTodosRouteRoute;
    };
    "/_app/todos/$listId": {
      id: "/_app/todos/$listId";
      path: "/$listId";
      fullPath: "/todos/$listId";
      preLoaderRoute: typeof AppTodosListIdRouteImport;
      parentRoute: typeof AppTodosRouteRoute;
    };
    "/_app/journal/new": {
      id: "/_app/journal/new";
      path: "/new";
      fullPath: "/journal/new";
      preLoaderRoute: typeof AppJournalNewRouteImport;
      parentRoute: typeof AppJournalRouteRoute;
    };
    "/_app/journal/$id": {
      id: "/_app/journal/$id";
      path: "/$id";
      fullPath: "/journal/$id";
      preLoaderRoute: typeof AppJournalIdRouteImport;
      parentRoute: typeof AppJournalRouteRoute;
    };
    "/_app/habits/$id": {
      id: "/_app/habits/$id";
      path: "/habits/$id";
      fullPath: "/habits/$id";
      preLoaderRoute: typeof AppHabitsIdRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/settings/billing/": {
      id: "/_app/settings/billing/";
      path: "/settings/billing";
      fullPath: "/settings/billing/";
      preLoaderRoute: typeof AppSettingsBillingIndexRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/settings/billing/upgrade": {
      id: "/_app/settings/billing/upgrade";
      path: "/settings/billing/upgrade";
      fullPath: "/settings/billing/upgrade";
      preLoaderRoute: typeof AppSettingsBillingUpgradeRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/settings/billing/success": {
      id: "/_app/settings/billing/success";
      path: "/settings/billing/success";
      fullPath: "/settings/billing/success";
      preLoaderRoute: typeof AppSettingsBillingSuccessRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
  }
}

interface AppJournalRouteRouteChildren {
  AppJournalIdRoute: typeof AppJournalIdRoute;
  AppJournalNewRoute: typeof AppJournalNewRoute;
  AppJournalIndexRoute: typeof AppJournalIndexRoute;
}

const AppJournalRouteRouteChildren: AppJournalRouteRouteChildren = {
  AppJournalIdRoute: AppJournalIdRoute,
  AppJournalNewRoute: AppJournalNewRoute,
  AppJournalIndexRoute: AppJournalIndexRoute,
};

const AppJournalRouteRouteWithChildren = AppJournalRouteRoute._addFileChildren(
  AppJournalRouteRouteChildren,
);

interface AppTodosRouteRouteChildren {
  AppTodosListIdRoute: typeof AppTodosListIdRoute;
  AppTodosCompletedRoute: typeof AppTodosCompletedRoute;
  AppTodosInboxRoute: typeof AppTodosInboxRoute;
  AppTodosUpcomingRoute: typeof AppTodosUpcomingRoute;
  AppTodosIndexRoute: typeof AppTodosIndexRoute;
}

const AppTodosRouteRouteChildren: AppTodosRouteRouteChildren = {
  AppTodosListIdRoute: AppTodosListIdRoute,
  AppTodosCompletedRoute: AppTodosCompletedRoute,
  AppTodosInboxRoute: AppTodosInboxRoute,
  AppTodosUpcomingRoute: AppTodosUpcomingRoute,
  AppTodosIndexRoute: AppTodosIndexRoute,
};

const AppTodosRouteRouteWithChildren = AppTodosRouteRoute._addFileChildren(
  AppTodosRouteRouteChildren,
);

interface AppRouteRouteChildren {
  AppJournalRouteRoute: typeof AppJournalRouteRouteWithChildren;
  AppTodosRouteRoute: typeof AppTodosRouteRouteWithChildren;
  AppCalendarRoute: typeof AppCalendarRoute;
  AppJourneyRoute: typeof AppJourneyRoute;
  AppIndexRoute: typeof AppIndexRoute;
  AppHabitsIdRoute: typeof AppHabitsIdRoute;
  AppHabitsIndexRoute: typeof AppHabitsIndexRoute;
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute;
  AppSettingsBillingSuccessRoute: typeof AppSettingsBillingSuccessRoute;
  AppSettingsBillingUpgradeRoute: typeof AppSettingsBillingUpgradeRoute;
  AppSettingsBillingIndexRoute: typeof AppSettingsBillingIndexRoute;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppJournalRouteRoute: AppJournalRouteRouteWithChildren,
  AppTodosRouteRoute: AppTodosRouteRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppJourneyRoute: AppJourneyRoute,
  AppIndexRoute: AppIndexRoute,
  AppHabitsIdRoute: AppHabitsIdRoute,
  AppHabitsIndexRoute: AppHabitsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsBillingSuccessRoute: AppSettingsBillingSuccessRoute,
  AppSettingsBillingUpgradeRoute: AppSettingsBillingUpgradeRoute,
  AppSettingsBillingIndexRoute: AppSettingsBillingIndexRoute,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
);

interface AuthRouteRouteChildren {
  AuthGoodbyeRoute: typeof AuthGoodbyeRoute;
  AuthOnboardingRoute: typeof AuthOnboardingRoute;
  AuthAuthCallbackRoute: typeof AuthAuthCallbackRoute;
  AuthAuthErrorRoute: typeof AuthAuthErrorRoute;
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthGoodbyeRoute: AuthGoodbyeRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthAuthCallbackRoute: AuthAuthCallbackRoute,
  AuthAuthErrorRoute: AuthAuthErrorRoute,
  AuthAuthLoginRoute: AuthAuthLoginRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
